# Generated by Django 4.2.14 on 2024-08-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
