# Generated by Django 4.2.14 on 2024-08-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='description',
        ),
    ]
