# Generated by Django 4.2.14 on 2024-08-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appointments_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='age',
            field=models.IntegerField(),
        ),
    ]
