# Generated by Django 4.2.14 on 2024-08-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_appointments_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='reason',
            field=models.CharField(default='general', max_length=20),
        ),
    ]
