# Generated by Django 4.2.14 on 2024-08-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_appointments_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
