# Generated by Django 4.2.14 on 2024-08-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appointments_patient_offline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
