# Generated by Django 4.2.14 on 2024-09-05 18:25

import authentication.manage
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkoyUQaux4PEUmEPGc7PodeN8XbgC4aOBsug&s', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.CharField(blank=True, max_length=10000, null=True)),
                ('experience', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('qualification', models.CharField(blank=True, default='MBBS', max_length=4, null=True)),
                ('qualification_doc', models.CharField(blank=True, default='MBBS', max_length=10000, null=True)),
                ('identity_doc', models.CharField(blank=True, default='MBBS', max_length=10000, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('rating_no', models.IntegerField(default=0)),
                ('time_slot', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=list, size=2), blank=True, default=list, null=True, size=None)),
                ('bio', models.CharField(blank=True, max_length=10000, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_category', to='doctors.doctorcategory')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('authentication.customuser',),
            managers=[
                ('objects', authentication.manage.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='doctorcategory',
            name='doctors',
            field=models.ManyToManyField(related_name='categories', to='doctors.doctors'),
        ),
    ]
