# Generated by Django 4.2.14 on 2024-08-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_category', to='doctors.doctorcategory'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='qualification',
            field=models.CharField(blank=True, default='MBBS', max_length=4, null=True),
        ),
    ]
