# Generated by Django 4.2.14 on 2024-08-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='rating_no',
            field=models.IntegerField(default=0),
        ),
    ]
